module.exports = {
  topCarBrands: [
    {
      id: 1,
      car_make: "Dodge",
      car_model: "Ram 3500",
      year: 2010,
      plate_number: "MRI0849",
    },
    {
      id: 2,
      car_make: "Infiniti",
      car_model: "G35",
      year: 2008,
      plate_number: "LBY2700",
    },
    {
      id: 3,
      car_make: "Isuzu",
      car_model: "Rodeo",
      year: 1994,
      plate_number: "ZRE3180",
    },
    {
      id: 4,
      car_make: "Ford",
      car_model: "Mustang",
      year: 1998,
      plate_number: "BQH8349",
    },
    {
      id: 5,
      car_make: "Panoz",
      car_model: "Esperante",
      year: 2006,
      plate_number: "BLZ0066",
    },
    {
      id: 6,
      car_make: "Suzuki",
      car_model: "SX4",
      year: 2007,
      plate_number: "BHX6305",
    },
    {
      id: 7,
      car_make: "Nissan",
      car_model: "Murano",
      year: 2007,
      plate_number: "RWE7539",
    },
    {
      id: 8,
      car_make: "Dodge",
      car_model: "Intrepid",
      year: 2001,
      plate_number: "IJN5156",
    },
    {
      id: 9,
      car_make: "Ford",
      car_model: "Escape",
      year: 2012,
      plate_number: "UHF0841",
    },
    {
      id: 10,
      car_make: "Volvo",
      car_model: "S80",
      year: 2004,
      plate_number: "RKR1162",
    },
  ],
};
